### ISSUE TITLE
Using subdomain instead of ports

### ISSUE THREAD

**Issue by jbendes** [snsinfu/reverse-tunnel#23]
What are your thoughts on using subdomains instead of ports? Is the main downside there just that you would need to consume a bunch of CPU running a proxy server redirecting subdomains to one another?

**Comment by snsinfu** [comment]
Nice idea! Certainly subdomain routing would be useful. I can't add the feature soon though.

rtun is made as a "dumb" pipe that just forwards TCP/UDP traffic. To route connections over subdomains, the tool needs to special-case and inspect HTTP requests. It's some work but it's possible.

**Comment by jbendes** [comment]
I'm glad to hear you like the idea! Yeah I've had a few issues with ports being blocked behind some networks. While it sounds like you have a lot going on right now, would you be totally against discussing me funding this work?

**Comment by snsinfu** [comment]
Thanks. I can enable GitHub sponsors but pull requests help more. :) My job sometimes gets really busy and I cannot work on this project for some months. Now I have time, so I'll work on this issue.

For now, hostname-based routing can be achieved by running an HTTP reverse proxy along with rtun-server (as implied in your post?). I document an example setup here. Run [Caddy](https://github.com/caddyserver/caddy) with the following config:

```console
$ cat Caddyfile
fooweb.example.com:80 {
	reverse_proxy localhost:8888
}
barapp.example.com:80 {
	reverse_proxy localhost:9999
}
$ sudo caddy run
```

and run `rtun-server` on the same host with this config:

```yaml
# rtun-server.yml
control_address: 0.0.0.0:4000

agents:
  - auth_key: xxxx
    ports: [8888/tcp]
  - auth_key: yyyy
    ports: [9999/tcp]
```

Then, requests to `http://fooweb.example.com` will be transferred to a web server running on the agent host having `auth_key: xxxx`.

**Comment by snsinfu** [comment]
*This is a design note.* I will add `http` forwarding type in addition to the existing `tcp` and `udp` forwarding types. An http forwarding entry will specify a hostname pattern, and rtun-server will route HTTP requests to agents accordingly. The Echo framework would be reused for implementation. The new server and agent configs will look like:

```yaml
# run-server.yml
agents:
  - auth_key: xxxx
    endpoints: [ 4567/tcp, http://*.example.com ]

  - auth_key: yyyy
    endpoints: [ 60000/udp, http://*.example.com:10080 ]

# rtun.yml
forwards:
  - endpoint: http://fooweb.example.com
    destination: localhost:8500
```

 I will rename `port(s)` config keys to `endpoint(s)`, keeping `port(s)` as aliases for compatibility.
